### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by pitpetterson** [1qaz2004/Marlin-bugfix-2.0.x-KP3S-RobinNanoV1.2#1]
Hi, great work would be nice to see the config .h and adv.h file, here as well

**Comment by 1qaz2004** [comment]
Hi added config .h and adv.h files

**Comment by pitpetterson** [comment]
cool stuff thanks for that ... I just thought it's easier if not to look at the facebook group files

**Comment by m00x-pixel** [comment]
Hi,
I have to open the current issue, where do i find the both config files, is it possible to add it to the repo?
So i want to try the firmware on my KP3S but want to mybe modify the settings. 

Thank you in advance.
