### ISSUE TITLE
Lots of troubles with this firmware

### ISSUE THREAD

**Issue by reivis** [1qaz2004/Marlin-bugfix-2.0.x-KP3S-RobinNanoV1.2#2]
Preheats at 170 degrees must by 200 degrees. Screen freese every time at preheat.
Selecting a file and the printer is automaticly changeing filement.
Screen say E heating and thats it, nothing is happening any more!
So on so on so on.
I think there are a lot off bugs in this firmware or I do something wrong.

**Comment by 1qaz2004** [comment]
Hey! This is pretty weird. Maybe you have a different temperature sensor or it is not installed correctly. Also check the EEPROM settings.

**Comment by reivis** [comment]
How do I do that?

**Comment by 1qaz2004** [comment]
You can use the Repetier-Host program to check the EEPROM settings and control the printer from a computer.

**Comment by reivis** [comment]
Ok, I wil try that. Thxs

**Comment by reivis** [comment]
When tessting I find a strange thing. When my printer must extrude he is doing intrude. So no filement is comming trough the nozzle. Any body an sollution?

**Comment by 1qaz2004** [comment]
The solution to the problem is to use the firmware for the inverted extruder motor. Robin_nano_E0_DIR true.bin

**Comment by reivis** [comment]
Ok, uploaded the recomended firmware. When starting a print bed and nozzle are heating up an then nothing any more. Waiting an our but nothing happens.

**Comment by 1qaz2004** [comment]
What printer model do you have? This firmware is for KP3S only. Check the printer is working with the stock firmware.

**Comment by reivis** [comment]
Yes I have a KP3S and with the stock firmware it's working fine.

**Comment by CTrost1993** [comment]
I seem to have also problems. I flashed this version but then nothing happend when I started a print (motors didn't move) so I went back to the stock Firmware for the KPS3 but the problems are still there. When I try to print something nothing happens and when I click on bed leveling the motors move in the wrong direction. Any clue what the problem might be?
Thank you
